//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2Stuff.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings activeEventTitleFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["activeEventTitleFont"]));
            }
            set {
                this["activeEventTitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings activeEventStatusFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["activeEventStatusFont"]));
            }
            set {
                this["activeEventStatusFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings activeEventTimerFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["activeEventTimerFont"]));
            }
            set {
                this["activeEventTimerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("active")]
        public string activeEventBackgroundImage {
            get {
                return ((string)(this["activeEventBackgroundImage"]));
            }
            set {
                this["activeEventBackgroundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double activeEventBackgroundOpacity {
            get {
                return ((double)(this["activeEventBackgroundOpacity"]));
            }
            set {
                this["activeEventBackgroundOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings inactiveEventTitleFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["inactiveEventTitleFont"]));
            }
            set {
                this["inactiveEventTitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings inactiveEventStatusFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["inactiveEventStatusFont"]));
            }
            set {
                this["inactiveEventStatusFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings inactiveEventTimerFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["inactiveEventTimerFont"]));
            }
            set {
                this["inactiveEventTimerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inactive")]
        public string inactiveEventBackgroundImage {
            get {
                return ((string)(this["inactiveEventBackgroundImage"]));
            }
            set {
                this["inactiveEventBackgroundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double inactiveEventBackgroundOpacity {
            get {
                return ((double)(this["inactiveEventBackgroundOpacity"]));
            }
            set {
                this["inactiveEventBackgroundOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings windowEventTitleFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["windowEventTitleFont"]));
            }
            set {
                this["windowEventTitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings windowEventStatusFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["windowEventStatusFont"]));
            }
            set {
                this["windowEventStatusFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GW2Stuff.FontSettings windowEventTimerFont {
            get {
                return ((global::GW2Stuff.FontSettings)(this["windowEventTimerFont"]));
            }
            set {
                this["windowEventTimerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inactive")]
        public string windowEventBackgroundImage {
            get {
                return ((string)(this["windowEventBackgroundImage"]));
            }
            set {
                this["windowEventBackgroundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double windowEventBackgroundOpacity {
            get {
                return ((double)(this["windowEventBackgroundOpacity"]));
            }
            set {
                this["windowEventBackgroundOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideTitleInGame {
            get {
                return ((bool)(this["hideTitleInGame"]));
            }
            set {
                this["hideTitleInGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,5,10,20")]
        public global::System.Windows.Thickness activeEventMargins {
            get {
                return ((global::System.Windows.Thickness)(this["activeEventMargins"]));
            }
            set {
                this["activeEventMargins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,5,10,20")]
        public global::System.Windows.Thickness inactiveEventMargins {
            get {
                return ((global::System.Windows.Thickness)(this["inactiveEventMargins"]));
            }
            set {
                this["inactiveEventMargins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,5,10,20")]
        public global::System.Windows.Thickness windowEventMargins {
            get {
                return ((global::System.Windows.Thickness)(this["windowEventMargins"]));
            }
            set {
                this["windowEventMargins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int defaultWorldId {
            get {
                return ((int)(this["defaultWorldId"]));
            }
            set {
                this["defaultWorldId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool clickThroughInGame {
            get {
                return ((bool)(this["clickThroughInGame"]));
            }
            set {
                this["clickThroughInGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool filterAssociation {
            get {
                return ((bool)(this["filterAssociation"]));
            }
            set {
                this["filterAssociation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool filterShowBuilds {
            get {
                return ((bool)(this["filterShowBuilds"]));
            }
            set {
                this["filterShowBuilds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool filterEventInactive {
            get {
                return ((bool)(this["filterEventInactive"]));
            }
            set {
                this["filterEventInactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool filterEventBoss {
            get {
                return ((bool)(this["filterEventBoss"]));
            }
            set {
                this["filterEventBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool filterEventTemple {
            get {
                return ((bool)(this["filterEventTemple"]));
            }
            set {
                this["filterEventTemple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double positionLeft {
            get {
                return ((double)(this["positionLeft"]));
            }
            set {
                this["positionLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double positionTop {
            get {
                return ((double)(this["positionTop"]));
            }
            set {
                this["positionTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double positionWidth {
            get {
                return ((double)(this["positionWidth"]));
            }
            set {
                this["positionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double positionHeight {
            get {
                return ((double)(this["positionHeight"]));
            }
            set {
                this["positionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dailyCompletionTime {
            get {
                return ((int)(this["dailyCompletionTime"]));
            }
            set {
                this["dailyCompletionTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection dailyCompletionList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["dailyCompletionList"]));
            }
            set {
                this["dailyCompletionList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PILOT NAME")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Merc Corps")]
        public string Faction {
            get {
                return ((string)(this["Faction"]));
            }
            set {
                this["Faction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Company {
            get {
                return ((string)(this["Company"]));
            }
            set {
                this["Company"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PUG")]
        public string Association {
            get {
                return ((string)(this["Association"]));
            }
            set {
                this["Association"] = value;
            }
        }
    }
}
