//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpArenaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpArenaEntities : DbContext
    {
        public ExpArenaEntities()
            : base("name=ExpArenaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwMatchMetric> vwMatchMetrics { get; set; }
        public virtual DbSet<vwVariantAssocMetric> vwVariantAssocMetrics { get; set; }
        public virtual DbSet<MechLoadout> MechLoadouts { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
