//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpArenaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMatchMetric
    {
        public Nullable<int> vwMatchMetricId { get; set; }
        public string time { get; set; }
        public string level { get; set; }
        public int victory { get; set; }
        public string victoryType { get; set; }
        public string matchType { get; set; }
        public string team { get; set; }
        public string name { get; set; }
        public string mech { get; set; }
        public int status { get; set; }
        public int matchscore { get; set; }
        public int kills { get; set; }
        public int assists { get; set; }
        public int damage { get; set; }
        public int ping { get; set; }
        public int lance { get; set; }
        public string AssociationName { get; set; }
        public int AssociationId { get; set; }
        public int PublishFlag { get; set; }
        public bool PublishingUserName { get; set; }
        public string MatchHash { get; set; }
        public int UserId { get; set; }
        public string PilotImage { get; set; }
        public string LanceName { get; set; }
        public string CompanyName { get; set; }
        public string FactionName { get; set; }
        public string ChassisName { get; set; }
        public string VariantName { get; set; }
        public int Tonnage { get; set; }
        public string WeightClass { get; set; }
        public int ChassisId { get; set; }
        public string RankName { get; set; }
    }
}
