//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpArenaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVariantAssocMetric
    {
        public Nullable<int> vwVariantAssocMetricId { get; set; }
        public int ChassisId { get; set; }
        public string WeightClass { get; set; }
        public int Tonnage { get; set; }
        public string ChassisName { get; set; }
        public string BaseVariantName { get; set; }
        public string AssociationName { get; set; }
        public string Assoc { get; set; }
        public string iconUrl { get; set; }
        public Nullable<int> matches { get; set; }
        public Nullable<int> WinPerc { get; set; }
        public Nullable<decimal> KDR { get; set; }
        public Nullable<decimal> DmgPM { get; set; }
        public Nullable<decimal> KPM { get; set; }
        public Nullable<decimal> DPM { get; set; }
        public Nullable<decimal> wins { get; set; }
        public Nullable<decimal> losses { get; set; }
        public Nullable<int> deaths { get; set; }
        public Nullable<int> kills { get; set; }
    }
}
